baseURL = "http://localhost/"
languageCode = "en-us"
title = "Torr's Coding Journey"
enableRobotsTXT = true
theme = "hextra"  # Set Hextra as the default theme

[pagination]
  pagerSize = 10

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  defaultTheme = "dark"
  description = "A blog and portfolio about Torr's journey learning to code."

  [params.navbar]
    links = [
      { name = "About", url = "/about/" },
      { name = "Blog", url = "/blog/" },
      { name = "Portfolio", url = "/portfolio/" }
    ]

[params.search]
  provider = "flexsearch"

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 2

[[menu.main]]
  name = "Portfolio"
  url = "/portfolio/"
  weight = 3

[[menu.main]]
  name = "Search"
  identifier = "search"
  url = "#"
  weight = 100
  [menu.main.params]
  type = "search"
